---
# Source: argo-cd/templates/argocd-configs/cluster-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: argocd-cluster-0
  namespace: "argocd"
  labels:
    helm.sh/chart: argo-cd-7.8.26
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: "v2.14.10"
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: production
  server: https://k8s.dansysadm.com:6443
  config: |
    {"tlsClientConfig":{"insecure":false,"caData":"","certData":"","keyData":""}}
