replicaCount: 1

image:
  repository: nginx
  tag: latest
  pullPolicy: Always
  repo: registry:5000

service:
  port: 8080

ingress:
  enabled: true
  className: traefik
  host: basic-app.local
  path: /
  domain: localhost

frontendruntimeconfig:
  enabled: false

# Environment variables to pass to all services
env: {}

# misql database configuration
misql:
  enabled: true
  image:
    repository: mysql
    tag: "8.0"