{{- if .Values.frontendruntimeconfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-runtime-config
data:
  config.js: |
    window.RUNTIME_CONFIG = {
      {{- range .Values.frontendruntimeconfig.services }}
      {{ . | upper }}_SERVICE_URL: "{{ $.Values.ingress.schema }}://{{ . }}.{{ $.Values.ingress.domain }}/{{ . }}",
      {{- end }}
      NOOP_SERVICE_URL: "http://localhost/noop"
    }
{{- end }}