apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: app
          image: "dansysadm.com/images/{{ .Release.Name }}:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SERVICE_PORT
              value: "{{ .Values.service.port }}"
              {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
              {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- if .Values.frontendruntimeconfig.enabled }}
          volumeMounts:
            - name: runtime-config
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
{{- end }}

{{- if .Values.frontendruntimeconfig.enabled }}
      volumes:
        - name: runtime-config
          configMap:
            name: frontend-runtime-config
{{- end }}