repositories:
  - name: jaegertracing
    url: https://jaegertracing.github.io/helm-charts

environments:
  dev:
    values:
      - env/dev.yaml

  production:
    values:
      - env/production.yaml

releases:

  - name: interest
    namespace: interest
    chart: ./charts/cv-app
    values:
      - {{ toYaml .Environment.Values | nindent 8 }}
      - ../../backend/interest/helm.values.yaml

  - name: education
    namespace: education
    chart: ./charts/cv-app
    values:
      - {{ toYaml .Environment.Values | nindent 8 }}
      - ../../backend/education/helm.values.yaml

  - name: qrcode
    namespace: qrcode
    chart: ./charts/cv-app
    values:
      - {{ toYaml .Environment.Values | nindent 8 }}
      - ../../backend/qrcode/helm.values.yaml

  - name: identity
    namespace: identity
    chart: ./charts/cv-app
    values:
      - {{ toYaml .Environment.Values | nindent 8 }}
      - ../../backend/identity/helm.values.yaml

  - name: experience
    namespace: experience
    chart: ./charts/cv-app
    values:
      - {{ toYaml .Environment.Values | nindent 8 }}
      - ../../backend/experience/helm.values.yaml

  - name: frontend
    namespace: frontend
    chart: ./charts/cv-app
    values:
      - {{ toYaml .Environment.Values | nindent 8 }}
      - ../../frontend/helm.values.yaml

  - name: jaeger
    namespace: jaeger
    createNamespace: true
    chart: jaegertracing/jaeger
    version: 0.71.0
    values:
      - ../jaeger/values.yaml