---
# Source: basic-app/templates/config-runtime.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-runtime-config
data:
  config.js: |
    window.RUNTIME_CONFIG = {
      EXPERIENCE_SERVICE_URL: "http://experience.dansysadm.com/experience",
      EDUCATION_SERVICE_URL: "http://education.dansysadm.com/education",
      INTEREST_SERVICE_URL: "http://interest.dansysadm.com/interest",
      IDENTITY_SERVICE_URL: "http://identity.dansysadm.com/identity",
      QRCODE_SERVICE_URL: "http://qrcode.dansysadm.com/qrcode",
      NOOP_SERVICE_URL: "http://localhost/noop"
    }
