---
# Source: basic-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: app
          image: "ghcr.io/daniellawrence/cv-frontend:main"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE_PORT
              value: "8080"
            - name: CONTENT_SHA1
              value: "dev-build"
            - name: BUILD_TIMESTAMP
              value: "unknown"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://jaeger-collector.jaeger:4317
            - name: OTEL_SERVICE_NAME
              value: frontend
            - name: CORS_ALLOWED_ORIGINS
              value: "https://dansysadm.com,https://education.dansysadm.com,https://experience.dansysadm.com,https://identity.dansysadm.com,https://interest.dansysadm.com,https://qrcode.dansysadm.com"
          resources:
            null
          volumeMounts:
            - name: runtime-config
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            failureThreshold: 1
            periodSeconds: 10

          startupProbe:
            httpGet:
              path: /healthz
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
      volumes:
        - name: runtime-config
          configMap:
            name: frontend-runtime-config
