---
# Source: basic-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qrcode
  labels:
    app: qrcode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qrcode
  template:
    metadata:
      labels:
        app: qrcode
    spec:
      containers:
        - name: app
          image: "ghcr.io/daniellawrence/cv-qrcode:main"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE_PORT
              value: "8080"
            # Database URL from environment or use default fallbacks per service
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: url
                  optional: true
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://jaeger-collector.jaeger:4317
            - name: OTEL_SERVICE_NAME
              value: qrcode
          resources:
            null
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            failureThreshold: 1
            periodSeconds: 10

          startupProbe:
            httpGet:
              path: /healthz
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
