service:
  type: ClusterIP

# Dev environment uses local registry with service-specific names
# Naming pattern: registry:5000/<service>:latest
image:
  repo: registry:5000
  tag: latest

misql:
  image:
    repository: dlawrence00/misql
    tag: 0.0.3

ingress:
  enabled: true
  className: traefik
  domain: localhost
  schema: http
