---
# Source: argo-cd/templates/extra-manifests.yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: cluster
  name: cluster-production
  namespace: argocd
stringData:
  config: '{"tlsClientConfig":{"insecure":false,"caData":"","certData":"","keyData":""}}'
  name: production
  server: https://k8s.dansysadm.com:6443
type: Opaque
