# Note: In dev environment, this will be overridden by env/dev.yaml to use registry:5000
image:
  repo: registry:5000
  tag: latest

frontendruntimeconfig:
  enabled: true
  services:
    - experience
    - education
    - interest
    - identity
    - qrcode
