server {
    listen 8080;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        add_header X-Content-SHA1 "${CONTENT_SHA1}";
        add_header X-Build-Timestamp "${BUILD_TIMESTAMP}";
        try_files $uri /index.html;
    }

    # Cache static assets aggressively
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}