repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint

  - repo: https://github.com/golangci/golangci-lint
    rev: v2.1.6
    hooks:
      - id: golangci-lint
        name: golangci-lint
        entry: bash -c 'for d in backend/*/; do [ -f "$d/go.mod" ] && (cd "$d" && golangci-lint run --fix); done'
        files: ^backend/
        pass_filenames: false
