repos:
  - repo: local
    hooks:
      - id: kubectl-validate
        name: kubectl-validate
        language: system
        entry: kubectl-validate
        args:
          - --local-crds=infra/crds/traefik
        files: ^infra/deployments/artifacts/

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        language: system
        entry: bash -c 'cd frontend && npm run lint'
        files: ^frontend/src/
        pass_filenames: false

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
        exclude: ^infra/crds/

  - repo: https://github.com/golangci/golangci-lint
    rev: v2.1.6
    hooks:
      - id: golangci-lint
        name: golangci-lint
        entry: bash -c 'for d in backend/*/; do [ -f "$d/go.mod" ] && (cd "$d" && golangci-lint run --fix); done'
        files: ^backend/
        pass_filenames: false

#  - repo: local
#    hooks:
#      - id: render-check
#        name: Render files check
#        entry: bash -c "./scripts/render.sh && git diff --exit-code infra/deployments/artifacts"
#        language: system
#        pass_filenames: false
