apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cv-prod
  namespace: argocd
spec:
  description: CV application - production environment
  sourceRepos:
    - https://github.com/daniellawrence/cv
  destinations:
    - namespace: "*"
      server: https://k8s.dansysadm.com:6443
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
