apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repo }}/{{ .Release.Name }}:{{ default "latest" .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SERVICE_PORT
              value: "{{ .Values.service.port }}"
              {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
              {{- end }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://jaeger-collector.jaeger:4317
            - name: OTEL_SERVICE_NAME
              value: {{ .Release.Name }}-backend
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- if .Values.frontendruntimeconfig.enabled }}
          volumeMounts:
            - name: runtime-config
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
{{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port }}
            failureThreshold: 1
            periodSeconds: 10

          startupProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port }}
            failureThreshold: 30
            periodSeconds: 10
{{- if .Values.frontendruntimeconfig.enabled }}
      volumes:
        - name: runtime-config
          configMap:
            name: frontend-runtime-config
{{- end }}