apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repo }}/{{ default .Release.Name .Values.image.name }}:{{ default "latest" .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SERVICE_PORT
              value: "{{ .Values.service.port }}"
            {{- if and .Values.buildMetadata .Values.buildMetadata.contentSha1 }}
            - name: CONTENT_SHA1
              value: {{ .Values.buildMetadata.contentSha1 | quote }}
            {{- end }}
            {{- if and .Values.buildMetadata .Values.buildMetadata.buildTimestamp }}
            - name: BUILD_TIMESTAMP
              value: {{ .Values.buildMetadata.buildTimestamp | quote }}
            {{- end }}
            {{- if .Values.misql.enabled }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: url
                  optional: true
            {{- end }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://jaeger-collector.jaeger:4317
            - name: OTEL_SERVICE_NAME
              value: {{ .Release.Name }}
            - name: CORS_ALLOWED_ORIGINS
              {{- if .Values.corsAllowedOrigins }}
              value: "{{ join "," .Values.corsAllowedOrigins }}"
              {{- else }}
              value: "{{ .Values.ingress.schema }}://{{ .Values.ingress.domain }}"
              {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- if .Values.frontendruntimeconfig.enabled }}
          volumeMounts:
            - name: runtime-config
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
{{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port }}
            failureThreshold: 1
            periodSeconds: 10

          startupProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port }}
            failureThreshold: 30
            periodSeconds: 10
{{- if .Values.frontendruntimeconfig.enabled }}
      volumes:
        - name: runtime-config
          configMap:
            name: frontend-runtime-config
{{- end }}