---
# Source: basic-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: experience
  labels:
    app: experience
spec:
  replicas: 1
  selector:
    matchLabels:
      app: experience
  template:
    metadata:
      labels:
        app: experience
    spec:
      containers:
        - name: app
          image: "dansysadm.com/images/experience:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE_PORT
              value: "8080"
          resources:
            null
