---
# Source: basic-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: experience
spec:
  type: ClusterIP
  selector:
    app: experience
  ports:
    - port: 8080
      targetPort: 
      protocol: TCP
