---
# Source: basic-app/templates/configmap-misql.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: misql-data
data:
  experience.yaml: |

    columns:
    - id
    - company
    - title
    - start_date
    - end_date
    - location
    - highlights
    - skills
    rows:
    - company: Block
      end_date: current
      highlights:
      - Led reliability for Block's telemetry platform
      - Platform migrations from Sumologic and NewRelic into Datadog
      - Managed full lifecycle of logging, metrics, and tracing for Afterpay, Cash, and
        Square
      - Agent skills development for including sentry management, k8s rightsizing, and
        datadog cost control
      - MCP development for internal log platform
      - Telemetry pipeline design and implementation
      - Mentoring, technical guidance and project planning
      id: block-sre
      location: Melbourne, Australia
      skills:
      - AWS
      - Datadog
      - Vector
      - OpenTelemetry
      - Kubernetes
      - Go
      - Sentry
      start_date: 2023-05
      title: Site Reliability Engineer, Observability
    - company: Okta
      end_date: 2023-05
      highlights:
      - Designed automated alert routing solution for on-call response optimization
      - Managed Wavefront configuration and operational administration
      - Provided production support and 24/7 on-call responsibilities
      id: okta-principal-sre
      location: Australia
      skills:
      - AWS
      - Go
      - Wavefront
      - Prometheus
      - AlertManager
      start_date: 2022-04
      title: Principal Site Reliability Engineer, Observability
    - company: Palo Alto Networks
      end_date: 2022-04
      highlights:
      - Led Tools, Monitoring, Metrics, and SCM/CI/CD SRE teams scaling
      - Architected and maintained CI/CD infrastructure
      - Platform scaling across configuration management, metrics, logs, CI/CD, and Kubernetes
      - Designed and implemented standard build templates
      - Core member of building out first GCP environment
      id: paloalto-techlead
      location: Melbourne, Australia
      skills:
      - GCP
      - Salt
      - Prometheus
      - GitLab
      - Terraform
      - Kubernetes
      - Python
      - Go
      start_date: 2017-11
      title: Technical Lead, SCM, CI/CD & Observability
    - company: LinkedIn
      end_date: 2017-11
      highlights:
      - SRE for 100+ applications across thousands of hosts in a service-oriented architecture
      - Mentoring and training my growing SRE team (3 to 12), while preserving a site-up
        and members first culture
      - Overhauled monitoring philosophy and implementation across multiple teams
      - Created and led many training & knowledge sharing efforts, speaking at external
        conferences.
      - Started SRE scorecard for service improvement across all of LinkedIn
      id: linkedin-staff-sre
      location: San Francisco Bay Area
      skills:
      - Python
      - Java
      - Go
      - Kafka
      start_date: 2015-02
      title: Staff Site Reliability Engineer, Jobs & Recruiter
    - company: Medibank Health Solutions
      end_date: 2015-02
      highlights:
      - Founding member of Cloud Services team scaling from 2 to 5 engineers
      - Built Medibank's first AWS environment and PCI compliance automation
      - Improved build times and reliability with docker & buildbot
      - Contributed to core code-base and implemented product and reliability features
      id: medibank-devops
      location: Melbourne, Australia
      skills:
      - AWS
      - Puppet
      - Python
      - django
      - docker
      start_date: 2013-03
      title: Linux & Cloud Services Engineer (DevOps)
    - company: Toll Holdings Limited
      end_date: 2013-03
      highlights: []
      id: toll-sysadmin
      location: Australia
      skills:
      - solaris
      - redhat
      - Python
      - django
      - nagios
      - graphite
      start_date: 2008-12
      title: Senior Linux & Unix Admin
    - company: IBM
      end_date: 2008-12
      highlights: []
      id: ibm-unix-admin
      location: Australia
      skills:
      - solaris
      - redhat
      - hpux
      - aix
      start_date: 2005-12
      title: Unix Admin
