image:
  name: cv-identity

# Database configuration - can be overridden by DATABASE_URL environment variable at runtime
database:
  url: "root@tcp(identity-db.identity:3306)/cv"

misql:
  enabled: true
  data:
    columns:
      - id
      - name
      - email
      - linkedin
    rows:
      - id: "dsl"
        name: "Daniel Lawrence"
        email: "dslawrence@protonmail.com"
        linkedin: "https://www.linkedin.com/in/dannylawrence/"
