apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cv-education-dev
  namespace: argocd
spec:
  project: cv-dev
  source:
    repoURL: https://github.com/daniellawrence/cv
    targetRevision: HEAD
    path: infra/deployments/artifacts/dev/education/basic-app/templates
  destination:
    server: https://kubernetes.default.svc
    namespace: education
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
