apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cv-interest-prod
  namespace: argocd
spec:
  project: cv-prod
  source:
    repoURL: https://github.com/daniellawrence/cv
    targetRevision: HEAD
    path: infra/deployments/charts/cv-app
    helm:
      releaseName: interest
      valueFiles:
        - ../../env/production.yaml
        - ../../../../backend/interest/helm.values.yaml
  destination:
    server: https://k8s.dansysadm.com:6443
    namespace: interest
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
