---
# Source: basic-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qrcode
  labels:
    app: qrcode
    deploy-timestamp: "1773208329"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qrcode
  template:
    metadata:
      labels:
        app: qrcode
        deploy-timestamp: "1773208329"
    spec:
      containers:
        - name: app
          image: "dansysadm.com/images/qrcode:facda8008011f7df63a663818f3d20681ccd0c6c"
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE_PORT
              value: "8080"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://jaeger-collector.jaeger:4317
            - name: OTEL_SERVICE_NAME
              value: qrcode-backend
          resources:
            null
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            failureThreshold: 1
            periodSeconds: 10

          startupProbe:
            httpGet:
              path: /healthz
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
