---
# Source: basic-app/templates/config-runtime.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-runtime-config
data:
  config.js: |
    window.RUNTIME_CONFIG = {
      EXPERIENCE_SERVICE_URL: "://experience.localhost/experience",
      EDUCATION_SERVICE_URL: "://education.localhost/education",
      INTEREST_SERVICE_URL: "://interest.localhost/interest",
      IDENTITY_SERVICE_URL: "://identity.localhost/identity",
      QRCODE_SERVICE_URL: "://qrcode.localhost/qrcode",
      NOOP_SERVICE_URL: "http://localhost/noop"
    }
