---
# Source: basic-app/templates/config-runtime.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-runtime-config
  labels:
    app: frontend
    deploy-timestamp: "1773208329"
data:
  config.js: |
    window.RUNTIME_CONFIG = {
      EXPERIENCE_SERVICE_URL: "http://experience.localhost/experience",
      EDUCATION_SERVICE_URL: "http://education.localhost/education",
      INTEREST_SERVICE_URL: "http://interest.localhost/interest",
      IDENTITY_SERVICE_URL: "http://identity.localhost/identity",
      QRCODE_SERVICE_URL: "http://qrcode.localhost/qrcode",
      OTEL_EXPORTER_OTLP_ENDPOINT:  "http://jaeger-collector.localhost/v1/traces"
    }
