apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cv-app-of-apps-prod
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/daniellawrence/cv
      targetRevision: HEAD
      path: infra/argocd/projects
    - repoURL: https://github.com/daniellawrence/cv
      targetRevision: HEAD
      path: infra/argocd/prod
  destination:
    server: https://k8s.dansysadm.com:6443
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
